{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOiif7f638dQ3YuqU5EGV9P",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/shashank0852/QuizMaster/blob/main/QuizMaster1.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "with open(\"questions.txt\", \"w\") as f:\n",
        "    f.write(\"\"\"#Category: Science\n",
        "Which gas is essential for human respiration?\n",
        "Oxygen|Carbon Dioxide|Nitrogen|Hydrogen\n",
        "0\n",
        "\n",
        "What is the chemical formula of water?\n",
        "H2O|CO2|O2|HCl\n",
        "0\n",
        "\n",
        "Which organ in the human body filters blood?\n",
        "Liver|Heart|Kidney|Lungs\n",
        "2\n",
        "\n",
        "What planet is known as the Red Planet?\n",
        "Venus|Mars|Jupiter|Mercury\n",
        "1\n",
        "\n",
        "Which is the hardest natural substance?\n",
        "Iron|Steel|Gold|Diamond\n",
        "3\n",
        "\n",
        "What is the main source of energy for Earth?\n",
        "Moon|Sun|Volcanoes|Wind\n",
        "1\n",
        "\n",
        "Which part of the plant conducts photosynthesis?\n",
        "Roots|Stem|Leaves|Flowers\n",
        "2\n",
        "\n",
        "What is the boiling point of water?\n",
        "50°C|90°C|100°C|120°C\n",
        "2\n",
        "\n",
        "#Category: Social\n",
        "Who was the first Prime Minister of India?\n",
        "Subhash Chandra Bose|Dr. B.R. Ambedkar|Mahatma Gandhi|Jawaharlal Nehru\n",
        "3\n",
        "\n",
        "What is the supreme law of India?\n",
        "Constitution|Preamble|Parliament|Judiciary\n",
        "0\n",
        "\n",
        "When did India become a republic?\n",
        "1947|1950|1952|1955\n",
        "1\n",
        "\n",
        "Which movement was led by Mahatma Gandhi in 1942?\n",
        "Quit India Movement|Non-Cooperation Movement|Civil Disobedience Movement|Swadeshi Movement\n",
        "0\n",
        "\n",
        "What is the capital of Tamil Nadu?\n",
        "Chennai|Bengaluru|Hyderabad|Kolkata\n",
        "0\n",
        "\n",
        "Which monument is known as the symbol of love?\n",
        "Charminar|Taj Mahal|Red Fort|Qutub Minar\n",
        "1\n",
        "\n",
        "Who wrote the Constitution of India?\n",
        "Sardar Vallabhbhai Patel|Dr. B.R. Ambedkar|Rajendra Prasad|Jawaharlal Nehru\n",
        "1\"\"\")\n",
        "\n",
        "\n"
      ],
      "metadata": {
        "id": "j4KchwGt-brL"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "class Question:\n",
        "    def __init__(self, question_text, options, correct_index):\n",
        "        self.question_text = question_text\n",
        "        self.options = options\n",
        "        self.correct_index = correct_index\n",
        "\n",
        "    def check_answer(self, user_input):\n",
        "        return user_input == self.correct_index\n",
        "\n",
        "class Quiz:\n",
        "    def __init__(self, category):\n",
        "        self.category = category\n",
        "        self.questions = []\n",
        "        self.score = 0\n",
        "\n",
        "    def add_question(self, question):\n",
        "        self.questions.append(question)\n",
        "\n",
        "    def start(self):\n",
        "        print(\"Quiz Topic: \" + self.category)\n",
        "        print(\"\")\n",
        "        question_number = 1\n",
        "        for q in self.questions:\n",
        "            print(\"Question \" + str(question_number) + \": \" + q.question_text)\n",
        "            for i in range(len(q.options)):\n",
        "                print(str(i) + \". \" + q.options[i])\n",
        "            try:\n",
        "                answer = int(input(\"Enter your answer (number): \"))\n",
        "                if q.check_answer(answer):\n",
        "                    print(\"Correct!\\n\")\n",
        "                    self.score += 1\n",
        "                else:\n",
        "                    print(\"Wrong! Correct answer is: \" + q.options[q.correct_index] + \"\\n\")\n",
        "            except:\n",
        "                print(\"Invalid input. Skipping question.\\n\")\n",
        "            question_number += 1\n",
        "\n",
        "    def show_result(self):\n",
        "        total = len(self.questions)\n",
        "        percent = (self.score / total) * 100\n",
        "        print(\"Your Score: \" + str(self.score) + \" out of \" + str(total))\n",
        "        print(\"Percentage: \" + str(round(percent, 1)) + \"%\")\n",
        "        if percent >= 80:\n",
        "            print(\"Excellent!\")\n",
        "        elif percent >= 50:\n",
        "            print(\"Good job!\")\n",
        "        else:\n",
        "            print(\"Try Again.\")\n",
        "\n",
        "class QuizManager:\n",
        "    def __init__(self, filename):\n",
        "        self.filename = filename\n",
        "        self.quizzes = {}\n",
        "\n",
        "    def load_questions(self):\n",
        "        current_category = None\n",
        "        current_quiz = None\n",
        "\n",
        "        with open(self.filename, 'r') as file:\n",
        "            lines = [line.strip() for line in file if line.strip()]\n",
        "            i = 0\n",
        "            while i < len(lines):\n",
        "                line = lines[i]\n",
        "                if line.startswith(\"#Category:\"):\n",
        "                    current_category = line.replace(\"#Category:\", \"\").strip()\n",
        "                    current_quiz = Quiz(current_category)\n",
        "                    self.quizzes[current_category] = current_quiz\n",
        "                    i += 1\n",
        "                else:\n",
        "                    question_text = lines[i]\n",
        "                    options = lines[i + 1].split('|')\n",
        "                    correct_index = int(lines[i + 2])\n",
        "                    question = Question(question_text, options, correct_index)\n",
        "                    current_quiz.add_question(question)\n",
        "                    i += 3\n",
        "\n",
        "    def start(self):\n",
        "        self.load_questions()\n",
        "        print(\"Available Categories:\")\n",
        "        categories = list(self.quizzes.keys())\n",
        "        for index in range(len(categories)):\n",
        "            print(str(index) + \". \" + categories[index])\n",
        "        try:\n",
        "            choice = int(input(\"Select a category (number): \"))\n",
        "            selected = categories[choice]\n",
        "            quiz = self.quizzes[selected]\n",
        "            quiz.start()\n",
        "            quiz.show_result()\n",
        "        except:\n",
        "            print(\"Invalid choice. Exiting.\")\n",
        "\n",
        "manager = QuizManager(\"questions.txt\")\n",
        "manager.start()\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "AP1KHTNm-X62",
        "outputId": "12fdca57-2196-40e5-8445-6243b2b86ae9"
      },
      "execution_count": null,
      "outputs": [
        {
          "metadata": {
            "tags": null
          },
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Available Categories:\n",
            "0. Science\n",
            "1. Social\n",
            "Quiz Topic: Science\n",
            "\n",
            "Question 1: Which gas is essential for human respiration?\n",
            "0. Oxygen\n",
            "1. Carbon Dioxide\n",
            "2. Nitrogen\n",
            "3. Hydrogen\n",
            "Correct!\n",
            "\n",
            "Question 2: What is the chemical formula of water?\n",
            "0. H2O\n",
            "1. CO2\n",
            "2. O2\n",
            "3. HCl\n",
            "Correct!\n",
            "\n",
            "Question 3: Which organ in the human body filters blood?\n",
            "0. Liver\n",
            "1. Heart\n",
            "2. Kidney\n",
            "3. Lungs\n",
            "Wrong! Correct answer is: Kidney\n",
            "\n",
            "Question 4: What planet is known as the Red Planet?\n",
            "0. Venus\n",
            "1. Mars\n",
            "2. Jupiter\n",
            "3. Mercury\n",
            "Invalid input. Skipping question.\n",
            "\n",
            "Question 5: Which is the hardest natural substance?\n",
            "0. Iron\n",
            "1. Steel\n",
            "2. Gold\n",
            "3. Diamond\n",
            "Invalid input. Skipping question.\n",
            "\n",
            "Question 6: What is the main source of energy for Earth?\n",
            "0. Moon\n",
            "1. Sun\n",
            "2. Volcanoes\n",
            "3. Wind\n"
          ]
        }
      ]
    }
  ]
}